// Approximate Nifty Midcap 150 constituent list (NSE symbols).
// This is a hand-maintained snapshot — NSE rebalances this index twice a
// year (Mar/Sep), so a handful of names may drift out of date between
// reviews. Update by cross-checking https://www.niftyindices.com when it
// starts looking stale.
export const MIDCAP_UNIVERSE = [
  "3MINDIA", "ABBOTINDIA", "ABCAPITAL", "ACC", "ATGL", "AIAENG", "ALKEM",
  "AJANTPHARM", "APARINDS", "ASTRAL", "BERGEPAINT", "ASHOKLEY", "BIOCON",
  "APLAPOLLO", "AUROPHARMA", "BDL", "BHARATFORG", "AUBANK", "BALKRISIND",
  "BANKINDIA", "BHEL", "APOLLOTYRE", "DABUR", "BLUESTARCO", "DIXON",
  "COFORGE", "COROMANDEL", "DALBHARAT", "BSE", "COLPAL", "COCHINSHIP",
  "CONCOR", "CRISIL", "FEDERALBNK", "ESCORTS", "ENDURANCE", "FLUOROCHEM",
  "FORTIS", "GMRAIRPORT", "GODREJIND", "HAVELLS", "GICRE", "GLAXO",
  "GODFRYPHLP", "GODREJPROP", "GLENMARK", "EXIDEIND", "HEXT", "INDUSTOWER",
  "HONAUT", "ICICIPRULI", "360ONE", "IPCALAB", "JKCEMENT", "INDIANB",
  "IRCTC", "ICICIGI", "IDFCFIRSTB", "HEROMOTOCO", "HINDPETRO", "IDEA",
  "HUDCO", "INDUSINDBK", "JSL", "KPITTECH", "LICHSGFIN", "MARICO",
  "KPRMILL", "JUBLFOOD", "LTTS", "MFSL", "LUPIN", "LAURUSLABS", "LTF",
  "MAHABANK", "JSWENERGY", "MCX", "KEI", "LINDEINDIA", "UNOMINDA", "MRF",
  "RADICO", "NAM-INDIA", "NAUKRI", "NATIONALUM", "OIL", "NIACL",
  "NLCINDIA", "OBEROIRLTY", "PAGEIND", "PRESTIGE", "PETRONET", "PIIND",
  "MOTILALOFS", "POWERINDIA", "NHPC", "NMDC", "OFSS", "POLYCAB", "MPHASIS",
  "PHOENIXLTD", "PERSISTENT", "PATANJALI", "SAIL", "SRF", "SJVN",
  "SCHAEFFLER", "SUZLON", "SBICARD", "RVNL", "SUNDARMFIN", "TATACOMM",
  "SUPREMEIND", "TATAINVEST", "TATAELXSI", "YESBANK", "TIINDIA", "THERMAX",
  "VOLTAS", "UBL", "UPL", "TORNTPOWER", "AIIL", "LLOYDSME", "KALYANKJIL",
  "POLICYBZR", "NYKAA", "PAYTM", "AWL", "LICI", "MEDANTA", "MANKIND",
  "JSWINFRA", "IREDA", "BHARTIHEXA", "PREMIERENE", "BAJAJHFL", "NTPCGREEN",
  "VMM", "SWIGGY", "WAAREEENER", "ITCHOTELS", "HDBFS", "ANTHEM",
  "LGEINDIA", "LENSKART", "GROWW", "ICICIAMC",
];
